WEB-BilgeAdam/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WEB_BilgeAdam.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "admin")]

    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WEB-BilgeAdam/Controllers/ClassroomsController.cs
using ApplicationCore_BilgeAdam.DTO_s.ClassroomDTO;
using ApplicationCore_BilgeAdam.Entities.Concrete;
using AutoMapper;
using Castle.Core.Resource;
using FluentValidation;
using FluentValidation.Results;
using Infrastructure_BilgeAdam.FluentValidator.ClassroomValidators;
using Infrastructure_BilgeAdam.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Microsoft.EntityFrameworkCore;
using WEB_BilgeAdam.Models.ViewModels;

namespace WEB_BilgeAdam.Controllers
{
    [Authorize(Roles = "admin,teacher, ikPersonel")]
    public class ClassroomsController : Controller
    {
        private readonly IClassroomRepository _classroomRepo;
        private readonly IMapper _mapper;
        private readonly ITeacherRepository _teacherRepo;

        public ClassroomsController(IClassroomRepository classroomRepo, IMapper mapper, ITeacherRepository teacherRepo)
        {
            _classroomRepo = classroomRepo;
            _mapper = mapper;
            _teacherRepo = teacherRepo;
        }

        public async Task<IActionResult> Index()
        {
            var classrooms = await _classroomRepo.GetFilteredList
                (
                    select: x => new ClassroomVM
                    {
                        Id = x.Id,
                        ClassroomNO = x.ClassroomNo,
                        ClassSize = x.Students.Where(x => x.Status != ApplicationCore_BilgeAdam.Entities.Abstract.Status.Passive).ToList().Count,
                        TeacherName = x.Teacher.FirstName + " " + x.Teacher.LastName,
                        TeacherId = x.Teacher.Id
                    },
                    where: x => x.Status != ApplicationCore_BilgeAdam.Entities.Abstract.Status.Passive,
                    orderBy: x => x.OrderByDescending(z => z.CreatedDate),
                    join: x => x.Include(z => z.Teacher).Include(z => z.Students)
                );

            return View(classrooms);
        }
        public async Task<IActionResult> CreateClassroom()
        {
            var model = new CreateClassroomDTO
            {
                Teachers = await _teacherRepo.GetByDefaults(x => x.Status != ApplicationCore_BilgeAdam.Entities.Abstract.Status.Passive)
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateClassroom(CreateClassroomDTO model)
        {
            model.Teachers = await _teacherRepo.GetByDefaults(x => x.Status != ApplicationCore_BilgeAdam.Entities.Abstract.Status.Passive);


            if (ModelState.IsValid)
            {
                if (await _classroomRepo.Any(x => x.ClassroomNo == model.ClassroomNo && x.Status != ApplicationCore_BilgeAdam.Entities.Abstract.Status.Passive))
                {
                    TempData["Warning"] = "Lütfen başka bir sınıf kodu seçiniz!";
                    return View(model);
                }
                else
                {
                    var entity = _mapper.Map<Classroom>(model);
                    await _classroomRepo.AddAsync(entity);
                    TempData["Success"] = "Sınıf eklendi!";
                    return RedirectToAction("Index", "Home");
                }
            }
            TempData["Error"] = "Lütfen aşağıdaki kurallara uyunuz!";
            return View(model);
        }

        public async Task<IActionResult> UpdateClassroom(int id)
        {
            if (id > 0)
            {
                var classroom = await _classroomRepo.GetById(id);
                if (classroom != null)
                {
                    var model = _mapper.Map<UpdateClassroomDTO>(classroom);
                    model.Teachers = await _teacherRepo.GetByDefaults(x => x.Status != ApplicationCore_BilgeAdam.Entities.Abstract.Status.Passive);
                    return View(model);
                }
            }
            TempData["Error"] = "Sınıf bulunamadı!";
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> UpdateClassroom(UpdateClassroomDTO model)
        {
            model.Teachers = await _teacherRepo.GetByDefaults(x => x.Status != ApplicationCore_BilgeAdam.Entities.Abstract.Status.Passive);
            if (ModelState.IsValid)
            {
                var entity = await _classroomRepo.GetById(model.Id);
                if (await _classroomRepo.Any(x => x.ClassroomNo == model.ClassroomNo && model.ClassroomNo != entity.ClassroomNo && x.Status != ApplicationCore_BilgeAdam.Entities.Abstract.Status.Passive))
                {
                    TempData["Warning"] = "Lütfen başka bir sınıf kodu seçiniz!";
                    return View(model);
                }
                else
                {
                    var classroom = _mapper.Map<Classroom>(model);
                    await _classroomRepo.UpdateAsync(classroom);
                    TempData["Success"] = "Sınıf güncellendi!";
                    return RedirectToAction("Index", "Home");
                }
            }
            TempData["Warning"] = "Lütfen aşağıdaki kurallara uyunuz!";
            return View(model);
        }

        public async Task<IActionResult> DeleteClassroom(int id)
        {
            if (id > 0)
            {
                var classroom = await _classroomRepo.GetById(id);
                if (classroom is not null)
                {
                    await _classroomRepo.DeleteAsync(classroom);
                    TempData["Success"] = "Sınıf silinmiştir!";
                    return RedirectToAction("Index", "Home");
                }
            }
            TempData["Error"] = "Sınıf bulunamamıştır!";
            return RedirectToAction("Index", "Home");
        }
    }
}

WEB-BilgeAdam/Controllers/StudentsController.cs
using ApplicationCore_BilgeAdam.DTO_s.ClassroomDTO;
using ApplicationCore_BilgeAdam.DTO_s.StudentDTO;
using ApplicationCore_BilgeAdam.Entities.Concrete;
using ApplicationCore_BilgeAdam.Entities.UserEntities.Concrete;
using AutoMapper;
using Infrastructure_BilgeAdam.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WEB_BilgeAdam.Models.ViewModels;

namespace WEB_BilgeAdam.Controllers
{

    //[Authorize(Roles = "ikPersonel")]
    //    [Authorize(Roles = "student")]
    public class StudentsController : Controller
    {
        private readonly IStudentRepository _studentRepo;
        private readonly IMapper _mapper;
        private readonly IClassroomRepository _classroomRepo;
        private readonly ITeacherRepository _teacherRepo;
        private readonly UserManager<AppUser> _userManager;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public StudentsController(IStudentRepository studentRepo, IMapper mapper, IClassroomRepository classroomRepo, ITeacherRepository teacherRepo, UserManager<AppUser> userManager, IWebHostEnvironment webHostEnvironment)
        {
            _studentRepo = studentRepo;
            _mapper = mapper;
            _classroomRepo = classroomRepo;
            _teacherRepo = teacherRepo;
            _userManager = userManager;
            _webHostEnvironment = webHostEnvironment;
        }

        [Authorize(Roles = "admin,ikPersonel")]
        public async Task<IActionResult> Index()
        {
            var students = await _studentRepo.GetFilteredList
                (
                    select: x => new StudentVM
                    {
                        Id = x.Id,
                        FirstName = x.FirstName,
                        LastName = x.LastName,
                        BirthDate = x.BirthDate,
                        Email = x.Email,
                        ClassroomName = x.Classroom.ClassroomName,
                        Average = x.Average,
                        CreatedDate = x.CreatedDate,
                        UpdatedDate = x.UpdatedDate
                    },
                    where: x => x.Status != ApplicationCore_BilgeAdam.Entities.Abstract.Status.Passive,
                    orderBy: x => x.OrderByDescending(z => z.CreatedDate),
                    join: x => x.Include(z => z.Classroom)
                );

            return View(students);
        }

        [Authorize(Roles = "admin,ikPersonel")]
        public async Task<IActionResult> CreateStudent()
        {
            var model = new CreateStudentDTO
            {
                Classrooms = await _classroomRepo.GetByDefaults(x => x.Status != ApplicationCore_BilgeAdam.Entities.Abstract.Status.Passive)

            };
            return View(model);
        }
        

        [Authorize(Roles = "admin,ikPersonel")]
        [HttpPost]
        public async Task<IActionResult> CreateStudent(CreateStudentDTO model)
        {
            model.Classrooms = await _classroomRepo.GetByDefaults(x => x.Status != ApplicationCore_BilgeAdam.Entities.Abstract.Status.Passive);
            if (ModelState.IsValid)
            {
                var student = _mapper.Map<Student>(model);
                await _studentRepo.AddAsync(student);
                TempData["Success"] = $"{student.FirstName} {student.LastName} öğrencisi sisteme kayıt edilmiştir!";
                return RedirectToAction("Index");
            }
            TempData["Error"] = "Lütfen aşağıdaki kurallara uyunuz!";
            return View(model);
        }

        [Authorize(Roles = "admin,ikPersonel")]
        public async Task<IActionResult> UpdateStudent(int id)
        {
            if (id > 0)
            {
                var student = await _studentRepo.GetById(id);
                if (student != null)
                {
                    var model = _mapper.Map<UpdateStudentDTO>(student);
                    model.Classrooms = await _classroomRepo.GetByDefaults(x => x.Status != ApplicationCore_BilgeAdam.Entities.Abstract.Status.Passive);
                    return View(model);
                }
            }
            TempData["Error"] = "Öğrenci bulunamadı!";
            return RedirectToAction("Index");
        }

        [HttpPost]
        [Authorize(Roles = "admin,ikPersonel")]
        public async Task<IActionResult> UpdateStudent(UpdateStudentDTO model)
        {
            model.Classrooms = await _classroomRepo.GetByDefaults(x => x.Status != ApplicationCore_BilgeAdam.Entities.Abstract.Status.Passive);
            if (ModelState.IsValid)
            {
                var student = _mapper.Map<Student>(model);
                await _studentRepo.UpdateAsync(student);
                TempData["Success"] = $"{student.FirstName} {student.LastName} adlı öğrenci güncellenmiştir!";
                return RedirectToAction("Index");
            }
            TempData["Warning"] = "Lütfen aşağıdaki kurallara uyunuz!";
            return View(model);
        }

        [Authorize(Roles = "admin,ikPersonel")]
        public async Task<IActionResult> DeleteStudent(int id)
        {
            if (id > 0)
            {
                var student = await _studentRepo.GetById(id);
                if (student != null)
                {
                    await _studentRepo.DeleteAsync(student);
                    TempData["Success"] = "Öğrenci silinmiştir!";
                    return RedirectToAction("Index");
                }
            }
            TempData["Error"] = "Öğrenci bulunamadı!";
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "admin,ikPersonel,student")]
        public async Task<IActionResult> ShowStudentClassroom(string userName)
        {
            var appUser = await _userManager.FindByNameAsync(userName);

            var student = await _studentRepo.GetByDefault(x => x.Email == appUser.Email);
            if (student != null)
            {
                var classroom = await _classroomRepo.GetById(student.ClassroomId);
                var teacher = await _teacherRepo.GetById(classroom.TeacherId);
                if (classroom is not null)
                {
                    var model = _mapper.Map<ClassroomStudentDTO>(classroom);
                    model.TeacherName = teacher.FirstName + " " + teacher.LastName;
                    return View(model);
                }
            }
            TempData["Error"] = "Bir şeyler ters gitti!";
            return RedirectToAction("Index", "Home");
        }


        [Authorize(Roles = "admin,ikPersonel,student,teacher")]
        public async Task<IActionResult> StudentExams(string userName)
        {
            var appUser = await _userManager.FindByNameAsync(userName);

            var student = await _studentRepo.GetByDefault(x => x.Email == appUser.Email);
            if (student != null)
            {
                var model = new StudentExamVM
                {
                    Exam1 = student.Exam1,
                    Exam2 = student.Exam2,
                    ProjectExam = student.ProjectExam,
                    ProjectPath = student.ProjectPath,
                    Average = student.Average
                };

                return View(model);
            }
            TempData["Error"] = "Öğrenci bulunamadı!";
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        [Authorize(Roles = "admin,ikPersonel,teacher")]
        public async Task<IActionResult> SetStudentExams(int id)
        {
            var student = await _studentRepo.GetById(id);
            if (student is not null)
            {
                var model = new StudentSetExamVM
                {
                    Id = student.Id,
                    FullName = student.FirstName + " " + student.LastName,
                    ClassroomId = student.ClassroomId
                };
                return View(model);
            }
            TempData["Error"] = "Öğrenci bulunamadı!";
            return RedirectToAction("ShowClassrooms", "Teachers", new { userName = User.Identity.Name });
        }

        [HttpPost, ValidateAntiForgeryToken]
        [Authorize(Roles = "admin,ikPersonel,teacher")]
        public async Task<IActionResult> SetStudentExams(StudentSetExamVM model)
        {
            var student = await _studentRepo.GetById(model.Id);
            if (student is not null) 
            {
                if (model.Exam1 != null)
                {
                    student.Exam1 = model.Exam1;
                }
                if (model.Exam2 != null)
                {
                    student.Exam2 = model.Exam2;
                }
                if (model.Project != null)
                {
                    string uploadDir = Path.Combine(_webHostEnvironment.WebRootPath, "students/projects");
                    string fileName = $"{Guid.NewGuid()}_{student.FirstName}_{student.LastName}_{model.Project.FileName}";
                    string filePath = Path.Combine(uploadDir, fileName);
                    FileStream fileStream = new FileStream(filePath, FileMode.Create);
                    await model.Project.CopyToAsync(fileStream);
                    fileStream.Close();
                    student.ProjectPath = fileName;
                }
                if (model.ProjectExam != null)
                {
                    student.ProjectExam = model.ProjectExam;
                }
                await _studentRepo.UpdateAsync(student);
                TempData["Success"] = "Sınav notları başarılı bir şekilde girilmiştir!";
                return RedirectToAction("ShowClassroomForTeacher", "Teachers", new { id = student.ClassroomId });
            }
            TempData["Error"] = "Öğrenci bulunamadı!";
            return RedirectToAction("ShowClassrooms", "Teachers", new { userName = User.Identity.Name });
        }

WEB-BilgeAdam/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>SB Admin 2 - Dashboard</title>

    <!-- Custom fonts for this template-->
    <link href="~/vendor/fontawesome-free/css/all.min.css"
          rel="stylesheet"
          type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet" />

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WEB_BilgeAdam.styles.css" asp-append-version="true" />
</head>

<body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">
        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion"
            id="accordionSidebar">
            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center"
               asp-area="Admin" asp-controller="Dashboard" asp-action="Index">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Admin Paneli</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0" />

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Anasayfa</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider" />


            <!-- Nav Item - Pages Collapse Menu -->
            <!-- Nav Item - Charts -->
            <li class="nav-item">
                <a class="nav-link" asp-area="Admin" asp-controller="Dashboard" asp-action="Index">
                     <i class="fas fa-fw fa-chart-area"></i>
                    <span>Admin Paneli</span>
                </a>
                <a class="nav-link" asp-area="Admin" asp-controller="Roles" asp-action="Index">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>Roller</span>
                </a>
                <a class="nav-link" asp-area="" asp-controller="Classrooms" asp-action="Index">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>Sınıflar</span>
                </a>
                <a class="nav-link" asp-area="" asp-controller="Teachers" asp-action="Index">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>Öğretmenler</span>
                </a>
                <a class="nav-link" asp-area="" asp-controller="Students" asp-action="Index">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>Öğrenciler</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block" />


        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <!-- Main Content -->
            <div id="content">
                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">


                        <!-- Nav Item - Alerts -->


                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle"
                               href="~/#"
                               id="userDropdown"
                               role="button"
                               data-toggle="dropdown"
                               aria-haspopup="true"
                               aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Admin</span>
                                <img class="img-profile rounded-circle"
                                     src="~/img/undraw_profile.svg" />
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <a class="dropdown-item" asp-controller="Account" asp-action="Edit" asp-area="">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Bilgileri Düzenle
                                </a>
                             
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item"
                                   href="~/#"
                                   data-toggle="modal"
                                   data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Çıkış Yap
                                </a>
                            </div>
                        </li>
                    </ul>
                </nav>
                <!-- End of Topbar -->
                <!-- /.container-fluid -->
                <div class="container">
                    <main role="main" class="pb-3">
                        <partial name="_NotificationPartial" />
                        @RenderBody()
                    </main>
                </div>
            </div>
            <!-- End of Main Content -->


       





            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->
        </div>
        <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="~/#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade"
         id="logoutModal"
         tabindex="-1"
         role="dialog"
         aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Çıkış Yapma Uyarısı</h5>
                    <button class="close"
                            type="button"
                            data-dismiss="modal"
                            aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    Çıkış yapmak istediğinize emin misiniz?
                </div>
                <div class="modal-footer">
                    <button class="btn btn-secondary"
                            type="button"
                            data-dismiss="modal">
                        Vazgeç
                    </button>
                    <a class="btn btn-primary" asp-area="" asp-controller="Account" asp-action="LogOut">Çıkış Yap</a>
                </div> 
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="~/vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/js/demo/chart-area-demo.js"></script>
    <script src="~/js/demo/chart-pie-demo.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js" integrity="sha512-37T7leoNS06R80c8Ulq7cdCDU5MNQBwlYoy1TX/WUsLFC2eYNqtKlV0QjH7r8JpG/S0GUMZwebnVFLPd6SU5yg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js" integrity="sha512-o6XqxgrUsKmchwy9G5VRNWSSxTS4Urr4loO6/0hYdpWmFUfHqGzawGxeQGMDqYzxjY9sbktPbNlkIQJWagVZQg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>





@* <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WEB_BilgeAdam</title>
    <link rel="stylesheet" href="~/~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/~/WEB_BilgeAdam.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <div class="navbar-collapse collapse">
                    <ul class="navbar-nav flex-grow-1 ">
                        <li class="nav-item d-flex ms-auto me-auto">
                            <a class="navbar-brand" asp-area="Admin" asp-controller="Dashboard" asp-action="Index">Admin Paneli</a>
                            <a class="nav-link text-white btn btn-outline-warning mx-2" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
                            <a class="nav-link text-white btn btn-outline-danger" asp-area="Admin" asp-controller="Roles" asp-action="Index">Roller</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_NotificationPartial" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted position-absolute bottom-0 d-flex align-items-center w-100" style="height:50px">
        <div class="container">
            &copy; 2023 - WEB_BilgeAdam - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js" integrity="sha512-37T7leoNS06R80c8Ulq7cdCDU5MNQBwlYoy1TX/WUsLFC2eYNqtKlV0QjH7r8JpG/S0GUMZwebnVFLPd6SU5yg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js" integrity="sha512-o6XqxgrUsKmchwy9G5VRNWSSxTS4Urr4loO6/0hYdpWmFUfHqGzawGxeQGMDqYzxjY9sbktPbNlkIQJWagVZQg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html> *@